### ISSUE TITLE
Getting profile activity data ?

### ISSUE THREAD

**Issue by timtensor** [nubelaco/proxycurl-linkedin-scraper#7]
Hello 
Is it possible , given that a set of profiles you can also list or output the activities from the profiles ? If so is it documented some where with an example ?

**Comment by bosmobosmo** [comment]
The [Person Profile Endpoint](https://nubela.co/proxycurl/docs#people-api-person-profile-endpoint) returns activities for the profile. Though bear in mind that the activities field is not guaranteed to be returned.
